### ISSUE TITLE
don't allow mathematical transformations on string data

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#11]
In gitlab by @rprasad on Aug 15, 2017, 17:00

*Created by: raprasad*

- Currently users can select a variable such as `country` and attempt to apply a transformation such as `d^2`
- Provide better error messaging via the client or rook
- Currently provides message below:

---
 
<img width="492" alt="screenshot_8_15_17__4_58_pm" src="https://user-images.githubusercontent.com/1036060/29336244-27c7d4a0-81db-11e7-9038-9f84fd9a6895.png">
error message from rook:

**Comment by raprasad** [comment]
In gitlab by @rprasad on Aug 25, 2017, 00:33

*Created by: tercer*

Good point.  We should make better use of the type defintions of variables from the metadata, when we trust them, and check whether transformations are meaningful against those types.

Privacy Tools is doing something more sophisticated in this regard for it's own version of transformations.  It's implemented in Haskell.  Probably more (and clumsier) than we need, but perhaps as we integrate that code in for the Privacy case, we can learn what works and implement something better here.

**Comment by Shoeboxam** [comment]
The error message as part of the manipulations pipeline is more helpful:
![image](https://user-images.githubusercontent.com/3630029/49066631-617b2580-f1e7-11e8-86f8-48f8670832df.png)

The warning appears as soon as the invalid transform is added to the pipeline.
