### ISSUE TITLE
Replication link is broken in D3M

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#111]
The replication link, at least in D3M mode, is breaking and producing:

<img width="1195" alt="screen shot 2018-01-29 at 1 09 22 am" src="https://user-images.githubusercontent.com/2085037/35495886-3e1414c4-0491-11e8-807b-41ac5dcd5655.png">

**Comment by Shoeboxam** [comment]
We no longer have the replication link. This functionality reminds me of the workspace sharing feature nowadays.
