### ISSUE TITLE
X-axis in bivariate plots needs a label

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#113]
The x-axis needs labeling in the bivariate plots in explore mode:

<img width="546" alt="screen shot 2018-01-29 at 2 01 44 am" src="https://user-images.githubusercontent.com/2085037/35497526-7e738e3a-0498-11e8-83e1-0d7893386c5a.png">
<img width="547" alt="screen shot 2018-01-29 at 2 01 30 am" src="https://user-images.githubusercontent.com/2085037/35497530-8071d3ea-0498-11e8-9413-8615af480fb3.png">

**Comment by Shoeboxam** [comment]
Cannot reproduce, I'm getting x axis labels on my branch. I was just cleaning up some css there tonight--
6e4f781b52f4852d8f45620a18645b0a8ee86a2e

**Comment by tercer** [comment]
That's great.  I was hopeful that perhaps /common or some other branch would clean this up as some artifact.  For reproduceability though, here is http://2ravens.org, in Chrome, which is generally running Master but perhaps a few commits behind:

<img width="556" alt="screen shot 2018-03-05 at 11 08 27 am" src="https://user-images.githubusercontent.com/2085037/36985737-0e7373f4-2066-11e8-8231-d00c5ddc677d.png">

Notice there's no "Hits" label on the _X_-axis.

**Comment by tercer** [comment]
@Shoeboxam Do you have a screenshot & branch where this is working?
