### ISSUE TITLE
favicon error

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#118]
This error crops up occasionally, with a favicon not able to load:

<img width="946" alt="screen shot 2018-02-01 at 12 43 14 am" src="https://user-images.githubusercontent.com/2085037/35662975-10a24bb4-06e9-11e8-80ed-4713077d4a9b.png">

**Comment by raprasad** [comment]
Add a favicon

**Comment by tercer** [comment]
Nice
