### ISSUE TITLE
Subsetting UI: how do you clear selected areas?

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#12]
In gitlab by @rprasad on Aug 16, 2017, 10:05

*Created by: raprasad*

How would a user clear the subset selections from the "country" plot below?

<img width="407" alt="tworavens_fearonlaitin" src="https://user-images.githubusercontent.com/1036060/29367181-12c08338-826a-11e7-89e5-d4a3f1299c71.png">

---

Scenario:
  - click subset
  - brush or select the plot for a particular variable
  - user decides clear the selection on the plot because
     - she/he doesn't want to subset at all 
     - she/he wants to clear the selection and choose other parts of the chart

Enhancement:
  - how can the user easily "clear"/reset the subset selection?
  - right now the user needs to either:
     - select everything in the chart to "reset" it
     - click "off" selected parts of the plot--can be difficult if the plot is divided into many sections

**Comment by raprasad** [comment]
In gitlab by @rprasad on Aug 25, 2017, 00:29

*Created by: tercer*

Not that this is a correct answer from a usability perspective, but the functionality is that a selected bar in the barplot, when clicked again would become unselected.

Obviously, when there are very many unique categories, and very many bars, landing on the correct category (let alone twice) is next to impossible.  So there needs to be a better approach.

One possibility that has been discussed is to have a way to enter expressions/predicates and then have the selection diagram show those expressions.

That would be useful even for continous variables, as for example when you want a specific lower bound to a region (say 2.7582) and can't get that precise value through brushing.

**Comment by Shoeboxam** [comment]
This functionality has changed/been implemented via manipulations.
