### ISSUE TITLE
Nominal tagging

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#131]
Variables that we ought to be able to tag as nominal, seem to not have the nominal tag available.   Here's an example:

<img width="222" alt="screen shot 2018-02-05 at 3 31 49 pm" src="https://user-images.githubusercontent.com/2085037/35827393-d598187e-0a89-11e8-844a-3d09eea24e55.png">

It is likely that they have that status, and we just can not presently undo nominal status, but if so, is not being represented in legend.  For example, the summary statistics from preprocess are correctly seeing this variable as nominal:

<img width="335" alt="screen shot 2018-02-05 at 3 35 15 pm" src="https://user-images.githubusercontent.com/2085037/35827516-4e3a0cd8-0a8a-11e8-92a5-224e1df55283.png">

(Also, somewhat relatedly we don't have a way to communicate this in the `CreatePipeline` call in TA2TA3 API, so rely on TA2 independently finding this information itself.)

**Comment by Shoeboxam** [comment]
Here's the expected behavior I am working towards:
Any variable of string type AFTER manipulations is nominal.

A nominal variable transformed (cast, binned, overwritten, etc) into a numeric is not labeled nominal.
A numeric variable transformed (cast, labeled, overwritten, etc) into a nominal is labeled nominal.

**Comment by Shoeboxam** [comment]
This was resolved in the experimental branch. All variables labeled nominal by preprocess, or manually by the user, get the nominal decoration. However, if the pebble also contains a tag with higher priority, the pebble will be decorated according to that tag instead.
