### ISSUE TITLE
Move Model and Explore links

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#136]
The model and explore links in the footer are not intuitve to find, for key functionality.  Should move elsewhere, and make more focal.

<img width="231" alt="screen shot 2018-02-06 at 2 55 12 pm" src="https://user-images.githubusercontent.com/2085037/35881114-c69f58ae-0b4d-11e8-8b45-552c9de798ca.png">

**Comment by Shoeboxam** [comment]
Addressed here:
13595d1927d25d58898f672c8670c8a87f003e4d
