### ISSUE TITLE
Arrows from Groups

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#138]
Arrows coming from groups have several quirks that need to addressed.

If you create a group, but do not have a dependent variable, then it goes to nowhere.

<img width="437" alt="screen shot 2018-02-06 at 7 05 16 pm" src="https://user-images.githubusercontent.com/2085037/35891160-e640030c-0b70-11e8-9bfe-746f239980ef.png">

If you have multiple dependent variables, only the first gets an arrow.

<img width="406" alt="screen shot 2018-02-06 at 7 07 33 pm" src="https://user-images.githubusercontent.com/2085037/35891187-04aa834e-0b71-11e8-9a91-14998aed0041.png">

Also, you can not add or remove an arrow from a group.

**Comment by Shoeboxam** [comment]
Hanging arrow addressed here: 12514ebea7f35c14ec05e0812aa9e296f33faf53

Is the expected behavior for multiple dependent variables a third convex hull?

**Comment by Shoeboxam** [comment]
This was added in experimental. The fix was to compute the intersection of the arrow and the line representing the extended radius from the nearest edge of the target convex hull
