### ISSUE TITLE
Univariate tree image needs resizing 

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#144]
The tree image generated by univariate explore is very large, with extensive white space at the bottom.   

This makes it impossible to switch between trees for different variables.  If you click the "univariate" tab again, then variable list will appear, below the current tree, but it is so far down to scroll, it is unlikely you would ever see it.

**Comment by tercer** [comment]
Maybe we could put the variable list above the tree image.

**Comment by Shoeboxam** [comment]
Fixed in:
7d63104
362e926
5263d76
