### ISSUE TITLE
Shrink pebble contents to scale within pebbles

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#150]
When pebbles shrink, such as in large groups, the distributions (and also the variable names) do not.  Sometimes that looks fine:
<img width="340" alt="screen shot 2018-02-11 at 3 10 27 pm" src="https://user-images.githubusercontent.com/2085037/36081757-2ab063d4-0f71-11e8-82b6-1c63ba949161.png">

Sometimes that looks terrible:
<img width="445" alt="screen shot 2018-02-11 at 3 00 27 pm" src="https://user-images.githubusercontent.com/2085037/36077853-c4ad2a64-0f3d-11e8-82cf-e3e5eb2894c9.png">

Should have solution to scale thinks nicely.

**Comment by Shoeboxam** [comment]
Fixed in 5931ed5341f9ea293f1a0cc5163b5406445a2f70
