### ISSUE TITLE
Decision tree failing on NIST cluster

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#153]
When a univariate exploration is requested, that is a decision tree is being built, on the NIST cluster we are getting a fail message on `treeapp`

<img width="512" alt="screen shot 2018-02-15 at 11 27 12 am" src="https://user-images.githubusercontent.com/2085037/36268273-0c979b62-1244-11e8-9b35-221a4db534a5.png">

**Comment by tercer** [comment]
Either `treeapp` is causing, or it's failure is causing an `end-search` command for NIST, which means the session with the user is then over.

<img width="1225" alt="screen shot 2018-02-15 at 11 40 13 am" src="https://user-images.githubusercontent.com/2085037/36268676-28c38ce6-1245-11e8-8a00-10acfa1292b7.png">

**Comment by tercer** [comment]
Request and response:

<img width="456" alt="screen shot 2018-02-15 at 11 43 08 am" src="https://user-images.githubusercontent.com/2085037/36268794-779133d2-1245-11e8-90be-7a25c8caf2be.png">

**Comment by tercer** [comment]
<img width="1367" alt="screen shot 2018-02-15 at 11 45 10 am" src="https://user-images.githubusercontent.com/2085037/36268895-bdafa5c4-1245-11e8-9627-867196f4b8c4.png">

**Comment by tercer** [comment]
Might be related to this problem where we're frequently reloading certain libraries:

<img width="691" alt="screen shot 2018-02-15 at 11 52 29 am" src="https://user-images.githubusercontent.com/2085037/36269290-d3b95774-1246-11e8-974d-b61cc14d9de4.png">

**Comment by kripanshu** [comment]
Can we get the response shown on the r server i.e the rooktreeapp.R response in the terminal? Might help to know what exactly the error is. 
I got this
 
![screen shot 2018-02-15 at 10 43 42 pm](https://user-images.githubusercontent.com/8504758/36292712-c0e9504e-12a1-11e8-8545-fe26701593d5.png)

**Comment by tercer** [comment]
@kripanshu That's a good lead.  It's hard to get NIST to give us extra info/logs/screenoutput, though not impossible.  Also, they won't have any resources for us to run again on their cluster until next week at least.  So for now, should explore what we can on our side.  I know it's a little blind.  

We do have this issue that we are almost constantly reloading the `rpart`package.  Can we work out why that is?  Is the right version not on CRAN?  Are we loading it differently than the other packages we are using?

**Comment by tercer** [comment]
Looks like packages have to be added here:
https://github.com/TwoRavens/TwoRavens/blob/master/setup/r-base/Dockerfile
to be put in the Docker image, and thus accessible in the NIST setup.

Fixed with this commit: 1a9cf1844d2ae9996aec75e156b2308f093b5591

Will close this issue once I have a chance to run this on the NIST cluster and confirm it now works.

**Comment by kripanshu** [comment]
I went through some blogs of CRAN mirror for it ( **for rpart, R version >R (≥ 2.15.0)** is needed which is not our problem)
I also discussed this with Raman Sir, he said the same thing about **putting the rpart library in the image**. Hope this fix runs.

**Comment by tercer** [comment]
Think this is fixed.  Will reopen if NIST testing shows this persists on their cluster.

**Comment by tercer** [comment]
This is failing on the GCE instance, so I'm opening up the issue again, and renaming:

<img width="978" alt="screen shot 2018-03-02 at 10 42 58 am" src="https://user-images.githubusercontent.com/2085037/36907426-a43c7320-1e06-11e8-8520-bad8690ebd1e.png">

**Comment by raprasad** [comment]
fixed with @tercer:
- `ravens-r-main` image on dockerhub needed a manual rebuild to include `rpart`
- `rooksource.R` wasn't including the `rpart` library. (except in dev mode where there is an attempt to update it)
