### ISSUE TITLE
make "solve problem" button as green (?)

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#163]

**Comment by tercer** [comment]
Turns green when "Submit Disc. Probs." has been correctly pressed (which I failed to do in demo).  For example:

<img width="1433" alt="screen shot 2018-02-26 at 4 47 40 pm" src="https://user-images.githubusercontent.com/2085037/36697357-ce7540d0-1b14-11e8-9032-9c9bc038fc03.png">

(Addressed as of #129)
