### ISSUE TITLE
Bring back subsetting functionality

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#165]
We removed subset functionality because it did not fit into the NIST testing framework, and because it is not straightforward in the TA2TA3 API.  However, this needs to be brought back into the main release, including likely for D3M mode.

**Comment by Shoeboxam** [comment]
Added subsetting functionality here: 89fb1b55c64923f60976beb37978bc585f6e7660

Trees of subsets may be added as a step in the manipulations pipeline.
