### ISSUE TITLE
Empty Data Citations

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#166]
If the data citation is empty, then the mouseover box should simply be removed, rather than come up blank.

<img width="723" alt="screen shot 2018-02-28 at 1 44 40 pm" src="https://user-images.githubusercontent.com/2085037/36806328-b34a9dbc-1c8d-11e8-9425-dcf1151e98bb.png">

**Comment by Shoeboxam** [comment]
In experimental, the popup content was switched to information in the datasetDoc. Regardless, should the popper content be empty, the Popper component will not draw a popover.
