### ISSUE TITLE
explore app writes to the ../assets directory

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#168]
`rookexplore.R` shouldn't write to the assets directory -- that's for "static" files.

```R
write(res, "../assets/result.json")
```

Similarly, `rookexplore.R` shouldn't read that `../assets/result.json` file either--e.g. that would only work with a single user accessing explore.

**Comment by aaron-lebo** [comment]
The original worked like that, I ported it over without worrying about
whether it was the right way.

It should probably just return the json in the response.

**Comment by raprasad** [comment]
I ran into it by chance--I was trying to cut extraneous directories from the `raven-r-service` docker image.   
- the entire repository is currently copied into the image but it mainly needs the `rook` directory

**Comment by kripanshu** [comment]
Please check : https://github.com/TwoRavens/TwoRavens/commit/7db7b398d53391562174c3063b6bee225c9041d8
