### ISSUE TITLE
explore app when using original group 

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#169]
We've assumed users of explore mode will wipe the variables and build a small subset of relationships to explore, such as:
<img width="378" alt="screen shot 2018-03-05 at 8 24 10 pm" src="https://user-images.githubusercontent.com/2085037/37009076-3b7c8f32-20b3-11e8-92d6-7977fe6985ab.png">

However, if you leave the default group setting of the problem definition, for example:
<img width="438" alt="screen shot 2018-03-05 at 8 14 28 pm" src="https://user-images.githubusercontent.com/2085037/37008822-010135a2-20b2-11e8-93ed-01a4c393742d.png">

Then if you click the explore you get:
<img width="534" alt="screen shot 2018-03-05 at 8 14 17 pm" src="https://user-images.githubusercontent.com/2085037/37008836-0dcad87e-20b2-11e8-9952-17fdb55793a4.png">

**Comment by Shoeboxam** [comment]
This seems to have been resolved by @vjdorazio with the modal.
