### ISSUE TITLE
Arrow heads missing when moving from explore to model mode.

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#197]
The links in model mode do not gain arrow heads when moving from explore to model mode.

<img width="862" alt="screen shot 2018-03-15 at 7 57 19 pm" src="https://user-images.githubusercontent.com/2085037/37496834-34474bbe-288b-11e8-8fe1-7e729caa5a5f.png">

This was previously a problem in #147.

**Comment by tercer** [comment]
Looks like this was always the case.  If you add links in explore mode, they don't have a direction to be expressed in model mode.  So need to decide what correct action is, and then solve.

**Comment by Shoeboxam** [comment]
Fixed in experimental. We don't even use the force diagram for explore anymore, but the diagram specification is diffed on mithril redraw, and the specification includes arrow directions.
