### ISSUE TITLE
Replace Pipeline ids with meaningful labels

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#217]
We are using pipeline ids in the results table, however, they have no meaning to the user.  In the future, the API can supply information from which to construct more meaningful labels for pipelines.  For the present we could replace these with something like "Solution 1", "Solution 2" (We have used "Model 1", "Model 2" in Dataverse mode).

**Comment by tercer** [comment]
Should likely solve #135 too.

**Comment by Shoeboxam** [comment]
The model type is extracted and displayed in the results table now. Speak up if `"Solution " + pipelineId` is still desired.
