### ISSUE TITLE
rooksubset.app crashes on o_196 seed data

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#22]
In gitlab by @rprasad on Aug 27, 2017, 22:50

*Created by: tercer*

Any attempt to subset variables using the o_196 dataset gives an error:

Error in if (nc == "character") { : argument is of length zero

The line within rooksubset that is failing is:  https://github.com/vjdorazio/TwoRavens/blob/dbee2a129c5c93677479408efe4b5bf85ad7e271/rook/rooksubset.R#L121

Because the data that is being passed for a new round of preprocessing in empty.

**Comment by raprasad** [comment]
In gitlab by @rprasad on Aug 27, 2017, 23:14

*Created by: tercer*

Some of the problem seems to be that the dataset is hardcoded in rooksubset when not in production:
https://github.com/vjdorazio/TwoRavens/blob/dbee2a129c5c93677479408efe4b5bf85ad7e271/rook/rooksubset.R#L44-L50

However, fixing that is not sufficient.

**Comment by tercer** [comment]
Subset has been removed from D3M mode entirely.  It is a new issue to restore subset functionality.
