### ISSUE TITLE
Cropped summary plots

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#225]
The summary plots that appear in the left panel on pebble mouseover have the wrong boundaries and are cropped:

<img width="609" alt="screen shot 2018-03-27 at 11 05 04 am" src="https://user-images.githubusercontent.com/2085037/37976320-3ea9250a-31af-11e8-9f7e-7f4682222918.png">

**Comment by tercer** [comment]
Hard code fix with 339028bd26dcacbef7a877347077be88d5fbddd6
Need more general solution.

**Comment by Shoeboxam** [comment]
These plots have been replaced with instances of the PlotVegaLite component, which handles automatic sizing.
