### ISSUE TITLE
EventData: dropping outliers for plots (date specifically)

### ISSUE THREAD

**Issue by vjdorazio** [TwoRavens/TwoRavens#230]
The date plot works as intended, but on load for phoenix it looks like this:

<img width="739" alt="screen shot 2018-03-27 at 4 08 29 pm" src="https://user-images.githubusercontent.com/3503987/37995197-2ed26838-31d9-11e8-97fb-8229b60092ac.png">

This is because the phoenix data has coded an event in 1923 for some reason. We should build in a check where if a year does not have a minimum of 10 events coded, we drop that year from this plot. Or, something along those lines, so outliers don't tank our distribution.

This is also an issue for aggregation:

<img width="358" alt="screen shot 2018-03-27 at 4 46 20 pm" src="https://user-images.githubusercontent.com/3503987/37996785-760abdf4-31de-11e8-9cf7-b2ab0a0e1ff4.png">

**Comment by Shoeboxam** [comment]
Resolved here:
https://github.com/TwoRavens/TwoRavens/commit/98671fde63e1149afc543515e60650c92db9d47e#diff-81fb890c7de08693e39841f865eb8c9dL192
