### ISSUE TITLE
EventData: simplified query page

### ISSUE THREAD

**Issue by vjdorazio** [TwoRavens/TwoRavens#243]
A page, or modal window, that allows users to submit queries directly. The idea is that if a user knows the data well, how it's structured and so forth, the user can directly enter the query and retrieve data. It's perhaps a way to bypass the existing "subset" mode and move straight to aggregation, for more advanced users. We would do very minimal restructuring of the user's input, and minimal if any validity checks. Rather, we just pass it through to the SQL database.

**Comment by Shoeboxam** [comment]
Resolved in: 6d5c72ae65aa166f02287978158b63cf5b32896e
