### ISSUE TITLE
Long variable names on problem discovery.

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#248]
NIST reports an issue where long variable names make the problem discovery table unusable.  Here long, means perhaps much greater than 50 characters:

>There is a glitch with your interface for the discovery task: the column names are so large (and the window is too small) and there is no scroll to the checkbox. I have to make the window big enough to be able to see the checkbox. Even though your text wraps, when it wraps it hides the "Task", "Metric" and Box field. This is another TA3 user interface issue.

Should perhaps abbreviate long column names.  

Seems similar to #191.

**Comment by Shoeboxam** [comment]
This is the relevant line:
https://github.com/TwoRavens/TwoRavens/commit/a7d655881aa48c3407d3917fc26d4c5120b94398#diff-78c1374a92d577f0013622f4efecbe23R104
