### ISSUE TITLE
Grammar for Groups: Collapse

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#260]
Groups of variables are currently depicted by colored convex hulls, filled with pebbles.

Should be allow these sets to collapse into one item, to abstract away the contents.

**Comment by Shoeboxam** [comment]
We have groups now.  

You have asked about opening collapsed groups. I consider grouping a necessary performance feature. We can increase the threshold, but at a certain point, we should build out UI that works independently of the force diagram for editing a problem. There is some functionality to this effect in the summary panel, but it takes a lot of clicking, typing and actions.
