### ISSUE TITLE
Actor switching between source and target render issue

### ISSUE THREAD

**Issue by marcusdeng22** [TwoRavens/TwoRavens#274]
In the actor menu, if I search for an actor and select some results, upon clicking the Target tab, the search results from Source are still displayed. The selected Source actors are not actually stored in the Target node, but is initially displayed.

Essentially, the Target actor list is not visually updated upon selecting the Target tab; it carries over the Source actor list until a filter is applied.

**Comment by Shoeboxam** [comment]
Thanks Marcus! My fault.
