### ISSUE TITLE
User Help: Links to tutorial materials

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#29]
*Created by: @tercer*

We should provide links to quickstart guides (perhaps http://2ra.vn/papers/tworavens-guide.pdf ) and a brief tutorial video, all embedded within the Frontend.  

For the present this could be only for the D3M mode, but is likely crucial for user testing during the dry run.

**Comment by raprasad** [comment]
_from @tercer_

Manual is up as a revised draft with a quickstart specific to D3M functionality.

Video is a quick demo of D3M materials, but should be revised to be more helpful.

**Comment by tercer** [comment]
These should probably be domain (D3M/Dataverse/Event Data) specific.  Presently they are set up assuming D3M users.

**Comment by tercer** [comment]
Manual partially updated to current d3m functionality.
