### ISSUE TITLE
Legend colors broken when returning from explore

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#304]
If you move to explore mode, and then return to model, the colors and fills for the legend break.
For example, it goes from:
<img width="165" alt="screen shot 2018-07-01 at 1 32 41 pm" src="https://user-images.githubusercontent.com/2085037/42137029-42193368-7d33-11e8-9f28-59f34ed95179.png">

To:
<img width="192" alt="screen shot 2018-07-01 at 1 30 40 pm" src="https://user-images.githubusercontent.com/2085037/42137021-381023cc-7d33-11e8-8755-941197512950.png">

**Comment by aaron-lebo** [comment]
This fix is in on 350-rp.

**Comment by vjdorazio** [comment]
merged. closing
