### ISSUE TITLE
Switch models between discovery table and center panel

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#305]
Models listed in the discovery table should be able to be sent to the center panel (in either model or explore mode).

Similarly, a model constructed in the center panel in explore mode, should be able to be sent to populate a new line on the discovery table.

**Comment by tercer** [comment]
From the #Design channel:

![20180702_163126_resized](https://user-images.githubusercontent.com/2085037/42830363-2e78ab12-89b9-11e8-93e7-250d58260dce.jpg)
![20180702_163741_resized](https://user-images.githubusercontent.com/2085037/42830368-3020a532-89b9-11e8-82aa-fea1fde34cfe.jpg)

**Comment by aaron-lebo** [comment]
*Models listed in the discovery table should be able to be sent to the center panel (in either model or explore mode).*

This part works in the explore-070218 branch.

**Comment by aaron-lebo** [comment]
The second section works, at least visually.

**Comment by aaron-lebo** [comment]
The second part works visually.

**Comment by tercer** [comment]
Terrific work.
