### ISSUE TITLE
store-user-problem call needs filename revision to accept path

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#318]
On better inspection, the spec on Task 1 requires certain files be written into their own directories.  

So presently `store-user-problem` takes `{filename: 'somename.json', data:[] }` which needs to continue to be acceptable.

However, it also needs to be able to take `{filename: 'somefolder/somename.json' , data:[]}` and create directory `somefolder` which won't have previously existed, in which to write `somename.json`.

**Comment by tercer** [comment]
Then I need to remember to correct the paths we're writing to in the UI.

**Comment by raprasad** [comment]
@tercer this has been added...

**Comment by tercer** [comment]
Works great.  Paths in UI fixed with cff036294f2866f39ee13588eee9c877780c5dae
