### ISSUE TITLE
remove tabs for tasks/subtasks/metrics

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#350]
There are three tabs devoted to tasks/subtasks/metrics, that mirror the Dataverse mode design of selecting a statistical model when Zelig models were offered.  It was a quick reuse of some prior existing functionality, that we have never returned to update.

These are very rarely changed by the user.  It is a lot of real visual real estate devoted to things one probably shouldn't touch.  Indeed we added locks to try to prevent test users from touching these as it's generally a mistake during testing.  So we should display this information more succinctly, and deemphasise the available choices that are really unavailable.

<img width="312" alt="screen shot 2018-07-30 at 12 05 52 am" src="https://user-images.githubusercontent.com/2085037/43377104-cb454874-938c-11e8-8c34-d708ceb2fde1.png">

**Comment by vjdorazio** [comment]
created branch 350-rp for this issue

**Comment by Shoeboxam** [comment]
Dropdown.js is a bit outdated in the develop branch of this repository, if you're having issues just replace it with this one that's more robust:
https://github.com/TwoRavens/common/blob/master/views/Dropdown.js

**Comment by aaron-lebo** [comment]
Multiple fixes on this branch ready for merge.

**Comment by vjdorazio** [comment]
merged 350-rp. closing this issue
