### ISSUE TITLE
ExecutePipeline command still there

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#365]
leftover from previous API

![image](https://user-images.githubusercontent.com/1036060/43642786-e8a9fbd6-96f6-11e8-85ac-7101e631b4b9.png)

**Comment by tercer** [comment]
Yes the call needs to be updated.  @vjdorazio is working on this page, but I can work on the API call it should trigger.

**Comment by tercer** [comment]
@vjdorazio Is reworking some of this tab, and then @tercer will rebuild the API call triggered by this button.
