### ISSUE TITLE
pipelineTable "score" column width

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#373]
Probably here: https://github.com/TwoRavens/TwoRavens/blob/3b727c709f17ccb5ba832c195bd37a8c0ac67625/assets/app/index.js#L238
Can we set something to increase the min width of the "score" column (column 3).  Currently it sometimes contains a "scoring" value, and sometimes only some numbers like "0.123".  As the word "scoring" appears and disappears, the width of the column changes, and the whole table shudders left and right as a knock-on effect.

<img width="286" alt="screen shot 2018-08-04 at 10 50 22 am" src="https://user-images.githubusercontent.com/2085037/43677690-42137caa-97d4-11e8-88c5-18bbdc81b582.png">

**Comment by Shoeboxam** [comment]
More specifically, right here:
https://github.com/TwoRavens/TwoRavens/blob/3b727c709f17ccb5ba832c195bd37a8c0ac67625/assets/app/index.js#L240

Tables may contain a number of elements aside from the tr, like `caption`, `thead`, `tfoot`, `colgroup`. The `colgroup` element specifically can be used to style column widths:
```
let colWidths = m('colgroup',
    m('col', {span: 1}),
    m('col', {span: 1}),
    m('col', {span: 1, width: '2em'}));
```

Any of these tags may be passed into the Table mithril component:
```
m(Table, {
    id: 'pipelineTable',
    tableTags: colWidths,
    ...
```
