### ISSUE TITLE
stored-request failures

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#374]
There can be numerous `stored-request` failures, if you're trying to plot predictions while the pipelineSearch is still running.  I think this is because there are three simultaneous streaming calls running, and the UI is having to poll on each of these, and calls are getting lost.

<img width="985" alt="screen shot 2018-08-04 at 11 06 40 am" src="https://user-images.githubusercontent.com/2085037/43677839-c7510b56-97d6-11e8-8998-7a1dd547f59d.png">

**Comment by raprasad** [comment]
note: `setInterval`

**Comment by tercer** [comment]
Pretty noticable improvements by changing some of the logic of which fields are being read on updates to judge if the update is ready, as well as slowing down the timing of polling when predicted values are being generated.

Will also add some structure to do less generation of predicted values on the fly on user clicks, and more prebuilt, which should distribute some of the polling load over time.

**Comment by tercer** [comment]
Getting errors triggered by the following:

<img width="1426" alt="screen shot 2018-08-09 at 11 12 17 pm" src="https://user-images.githubusercontent.com/2085037/43937125-d4c683e0-9c29-11e8-9028-93cf9bbdccae.png">

Might put back some of the `(typeof resXX != 'undefined')` checks into the logic.

**Comment by raprasad** [comment]
- some fixes in
- two additional issues to mitigate this: #388 and #397
