### ISSUE TITLE
Add some way to signify the meaning of "meaningful"

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#382]
We have a column that is intended to provide insight from the testing process of when a user finds a suggested discovered problem "meaningful".  We're reusing a submission checkbox that used to be for selecting problems for submission.

Somehow, with limited space available, we need to convey what this is column of checkmarks is for.

<img width="781" alt="screen shot 2018-08-06 at 1 14 48 am" src="https://user-images.githubusercontent.com/2085037/43743482-09631862-99a4-11e8-846b-c2ebf78fd238.png">

**Comment by vjdorazio** [comment]
merged branch 382-meaningful with the  tooltip info

**Comment by tercer** [comment]
Works.  Might be good to add some/any page text.  The tooltip has a browser specific delay, that can't be adjusted.

Meaningful values are now correctly being written to labels.csv file also.
