### ISSUE TITLE
Get Green Button Nudges to Cue Off Environment

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#383]
Previously, in the testing environment, users had to complete Task 1 and then Task 2.  So the green buttons that nudged users along used that workflow.  

Now, however, users will either be given a Task 1 OR a Task 2 assignment.  Never both in a single session.  The TA3 system should be able to determine from the information available in the config file and environment variables, which of the two is the setting.  

From this, the Green button prompts should cue respectively.

**Comment by Shoeboxam** [comment]
The commit reference was mislabeled. Please ignore the reference.
