### ISSUE TITLE
Explore mode in Discovery select issue

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#390]
When in explore mode, triggered with the Discovery table open, the current problem highlighted in the table can be explored, but no other problem can be clicked/selected.

<img width="1397" alt="screen shot 2018-08-07 at 5 12 50 pm" src="https://user-images.githubusercontent.com/2085037/43802943-593da0fc-9a65-11e8-9dbf-ff7128eafb73.png">

**Comment by aaron-lebo** [comment]
@tercer I can't recreate this, can you give some more details about how you triggered it?

**Comment by tercer** [comment]
@aaron-lebo If I press the following buttons everything is fine:
"Discovery" -> Select a problem -> "Explore" -> "Go"
and I get the right graphs.

If I go:
"Discovery" -> Select a problem -> "Explore" -> Click some other problem on the explore page

Then nothing is highlighted pink, and "Go" leads to a blank page.

**Comment by aaron-lebo** [comment]
Still not getting an error on 350-rp. Is this on develop? It ran fine on
Chromium, too. Trying to narrow down what the difference could be.

**Comment by tercer** [comment]
Interesting.  I was running Develop, with Safari and Chrome.

**Comment by tercer** [comment]
Oh - so I should test in 350-rp?

**Comment by tercer** [comment]
Yes.  Can confirm it's not a problem in 350-rp.

**Comment by tercer** [comment]
So 350-rp is now merged into develop, but the problem seems have come back in develop.

**Comment by tercer** [comment]
Fixed with 13d7a3f6d58c9c6ae4b78d5715d3227faee05439.  Thanks @aaron-lebo !
