### ISSUE TITLE
Very long dataset names put "Mark Problem Finished" button is odd header location

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#407]
<img width="1440" alt="screen shot 2018-08-10 at 2 47 37 pm" src="https://user-images.githubusercontent.com/2085037/43975698-7c6cbe34-9cac-11e8-89cb-6f6fe5c18321.png">

**Comment by Shoeboxam** [comment]
Resolved in experimental. The header has been replaced with a header component that turns into a hamburger if necessary.
