### ISSUE TITLE
stored-request failures

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#411]
There can still be long sequences of stored-request and related streaming failures.  Building up a catalog of the issues:

This one can happen tens of times in a row, bascially bringing down the system from a usability perspective:
<img width="545" alt="screen shot 2018-08-17 at 4 49 59 pm" src="https://user-images.githubusercontent.com/2085037/44288350-0c219680-a23e-11e8-8572-ed83ec8b53e9.png">
(Example is ACLED)

**Comment by raprasad** [comment]
should be fixed with websockets.
