### ISSUE TITLE
Green nudges disappear if you move into and out of explore mode.

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#430]
The nudges to move users to discovery or problem solution disappear when you toggle into and out of explore mode.  This may have tripped up a user in testing.  

<img width="175" alt="screen shot 2018-09-03 at 1 40 07 am" src="https://user-images.githubusercontent.com/2085037/44969264-6eef7f00-af1a-11e8-971b-993569abff88.png">

**Comment by Shoeboxam** [comment]
This was solved in experimental. The green nudges are stored in global variables now, so they persist after the dom is reconstructed.
