### ISSUE TITLE
Removing and reintroducing pebble does not return variable density

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#446]
If you remove a variable from the center panel, and then reintroduce it, the histogram or kernel density does not return to the pebble.

<img width="364" alt="screen shot 2018-12-20 at 4 10 54 pm" src="https://user-images.githubusercontent.com/2085037/50311096-03ea9980-0472-11e9-800c-c2dfc00c3b3a.png">

**Comment by Shoeboxam** [comment]
This is fixed in experimental.
