### ISSUE TITLE
Ladda spinner gone from Solve Problem button

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#458]
Ladda spinner has disappeared from Solve Problem button.  Currently looks like:

<img width="222" alt="screen shot 2019-01-04 at 10 52 01 am" src="https://user-images.githubusercontent.com/2085037/50696992-f6efad80-100e-11e9-9ebf-8dbfb56931dd.png">

**Comment by Shoeboxam** [comment]
Duplicate issue. The button no longer exists in experimental.
