### ISSUE TITLE
Legend hidden behind results right panel

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#462]
The legend for the directed graph is hidden behind the right panel results tab:

<img width="1096" alt="screen shot 2019-01-04 at 4 24 36 pm" src="https://user-images.githubusercontent.com/2085037/50711782-44830f00-103d-11e9-8f53-072213d594af.png">
<img width="1098" alt="screen shot 2019-01-04 at 4 24 18 pm" src="https://user-images.githubusercontent.com/2085037/50711785-464cd280-103d-11e9-8e63-a18aa51f59d8.png">

**Comment by Shoeboxam** [comment]
Resolved in experimental.
