### ISSUE TITLE
Move problem discovery into separate rook app

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#463]
Problem discovery functions were bolted onto the preprocess app as a convenience for the last deadline.  Need their own seperate call, particularly since basic preprocess routines are migrating to independent service.

**Comment by Shoeboxam** [comment]
What is your opinion on leaving discovery inside preprocess, so that the dataset need only be loaded once? I was thinking flags could be sent to the preprocess app to enable/disable summaries, discovery, etc.

**Comment by Shoeboxam** [comment]
Resolved in `705-preprocess`.
