### ISSUE TITLE
add sign in/log out to top right of pebbles page

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#48]
from 11/21 meeting
![dev_links](https://user-images.githubusercontent.com/1036060/33225649-b61bc1ea-d149-11e7-8a7a-d171277d9a12.png)
![login](https://user-images.githubusercontent.com/1036060/33225655-c71ba4a6-d149-11e7-87eb-768deacd49ba.png)

**Comment by tercer** [comment]
@aaron-lebo fixed the pulldown, and finally I populated this pulldown with various links, not all of which might be appropriate.  Is set up to create different link lists, depending on field `username` which currently only distinguishes between someone not logged in, and everyone else, but could use this approach to add links for different classes of users (devs, admins, project owners).

<img width="307" alt="screen shot 2018-01-26 at 6 34 45 pm" src="https://user-images.githubusercontent.com/2085037/35465132-f9b87b96-02c7-11e8-896f-b2b46e52eb50.png">

**Comment by tercer** [comment]
Reasonable links put in to pulldown.

<img width="263" alt="screen shot 2018-02-08 at 11 06 33 am" src="https://user-images.githubusercontent.com/2085037/35983512-29abc8e2-0cc0-11e8-8a1d-d8dd954df41d.png">
