### ISSUE TITLE
Column renaming primitive?

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#560]
also see #548 

---

Do we create a column renaming primitive that updates:
1 - data
2 - problemDoc
3 - datasetDoc

- Should this be a primitive?
- Code from rook should be moved to TA3 python

**Comment by Shoeboxam** [comment]
Resolved in d9e67d7b033f3014d6a9f2bae3f04cecd912702d

The original column names are preserved. Calls to rook preprocess and mongo import use the deduplicated column names from `DuplicateColumnRemover`.
