### ISSUE TITLE
Model controls

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#565]
I realize this might go away with the experimental branch, however, so problems with contols. 

The link-all button doesn't work.
<img width="72" alt="Screen Shot 2019-05-06 at 1 29 23 PM" src="https://user-images.githubusercontent.com/2085037/57243081-351fcc80-7003-11e9-8f3c-dc2dd53e99c1.png">

The wipe button leaves the group boundary and arrows in place:
<img width="511" alt="Screen Shot 2019-05-06 at 1 29 48 PM" src="https://user-images.githubusercontent.com/2085037/57243120-4a94f680-7003-11e9-8a0a-988fe6bad7e8.png">

And then after wipe, if you reintroduce variables, they sit in the top left corner of the screen:
<img width="92" alt="Screen Shot 2019-05-06 at 1 29 53 PM" src="https://user-images.githubusercontent.com/2085037/57243150-600a2080-7003-11e9-8e11-a8873fe16fa4.png">

**Comment by Shoeboxam** [comment]
Resolved in experimental.
