### ISSUE TITLE
Ladda spinner broken

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#566]
Ladda spinner on Solve This Problem button broken:

<img width="221" alt="Screen Shot 2019-05-07 at 2 29 16 AM" src="https://user-images.githubusercontent.com/2085037/57276572-0ab82880-7070-11e9-82a0-f0c8f90c524d.png">

**Comment by Shoeboxam** [comment]
This button no longer exists after experimental.

There is, however, a component that should handle this more cleanly going forward:
```
m(ButtonLadda, {
    activeLadda: isSpinning, 
    onclick: () => console.log('I was clicked')
}, 'Solve This Problem')
```

It was too easy to forget some of the styling/classes or lose the handle to the ladda object before.
