### ISSUE TITLE
small UI tweaks

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#653]
- [x] datamart, remove "exact match" switch
- [x] datamart, for Augment, add a "Save as New" button to the modal (or see below)

**Comment by tercer** [comment]
Discovered Problems: 
Table width bounces around based on length of problem row.

In explore mode tiles, target variables are graphed, but not named.

In explore mode tiles, list of predictors in selected tile is copied into all other tiles.

Description dialog not appearing at foot of table (in accled_reduced).


(Did we intentionally remove the submit task 1 button?)


Augment:  Keywords in problem doc not appearing in keyword dialog box.


Is “Save As New” really necessary step before augmentation?  Can we find a way to skip?


Model:  When many predictors, could there be a way to open up the group to see the small pebbles

Results:

Confusion matrix title off-center (accred-reduced). 
Should maybe color code the diagonal somehow.  Maybe outline the cells on the diagonal?.

Models scored by accuracy should be ordered highest to lowest.

Importance graphs unreadable if labels too long.

Fairly long delay to blocking modal window when final solution selected.  No clear user signal something is happening.

**Comment by raprasad** [comment]
Task 1. Minor. Can be post-eval.  "meaningful" checkbox remains for Current Problem after discovered problems are submitted.

![image](https://user-images.githubusercontent.com/1036060/61540306-62c5c080-aa0b-11e9-8bb6-dfd04507fc72.png)

**Comment by raprasad** [comment]
- [ ] peek not resetting after data augment

**Comment by raprasad** [comment]
- [ ] "Search by Query" should be "Search" or "Search by Keywords"

**Comment by tercer** [comment]
@raprasad We hit the big points for the eval release, but there are left over pieces.  Should I break up the remaining as new issues, and then close this?

**Comment by raprasad** [comment]
@tercer Yes, break it up and close

**Comment by tercer** [comment]
I've checked off the issues I found to be completed (although may have missed some that were actually addressed if hard to check) and built new issues for those that remain uncompleted:
#725 #726 #727 #728 #729 #730 #731 #732

Closing this issue.
