### ISSUE TITLE
Failure during augmentation

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#672]
Maybe makedocs is failing when augmented data returns?  The following is celery error when augmenting taxi data with yellow cab 2017:

<img width="1083" alt="Screen Shot 2019-08-01 at 2 58 24 PM" src="https://user-images.githubusercontent.com/2085037/62319895-fa47fc00-b46c-11e9-993a-372c595aa30a.png">

**Comment by raprasad** [comment]
- [ ] ^ error with rook_params was old/fixed on developed
- [ ] typo fixed for showing pebbles, even if data is empty
- [ ] try to run augment with dataset (new endpoint)
