### ISSUE TITLE
Histograms broken

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#698]
In baseball, histograms are broken.  Either because there is an issue in the data we are no longer dealing with, typing is off, something else in preprocess is off, or something is being misread in preprocess.

<img width="207" alt="Screen Shot 2019-10-01 at 10 19 57 AM" src="https://user-images.githubusercontent.com/2085037/65970845-3da2f480-e435-11e9-9ff4-7d7775e21f97.png">
<img width="195" alt="Screen Shot 2019-10-01 at 10 19 10 AM" src="https://user-images.githubusercontent.com/2085037/65970847-3da2f480-e435-11e9-9487-678113984ec2.png">
<img width="201" alt="Screen Shot 2019-10-01 at 10 18 50 AM" src="https://user-images.githubusercontent.com/2085037/65970848-3da2f480-e435-11e9-96bc-6b03d96ebfcc.png">
<img width="201" alt="Screen Shot 2019-10-01 at 10 22 46 AM" src="https://user-images.githubusercontent.com/2085037/65970959-7511a100-e435-11e9-8c9c-496ed5c217ab.png">

**Comment by tercer** [comment]
Issue is Mongo hasn't finished loading data.

**Comment by Shoeboxam** [comment]
Resolved in `automl-backends`, preprocess won't load until mongo has finished loading data.
