### ISSUE TITLE
Use pypi preprocess in TwoRavens

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#705]
## server side

- update metadata service pypi
- integrate into PreprocessUtil
- interim adjustment for discovered problems--use the "disco" section from the R preprocess

## frontend
- Make distinct disco call 
- UI, variable naming
  - other adjustments related to schema changes

**Comment by Shoeboxam** [comment]
I finished the remaining parts for this (frontend integration, discovery app, report) in the `705-preprocess` branch. Ready to be merged.
