### ISSUE TITLE
Switch Datasets for Demo

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#713]
- Part of #710.
- Switching datasets is possible by changing TA2 settings:
   - For TA2 environment variables, point input/output directories 1-level higher than usual.  
      - e.g. instead of input at `test_data/DA_POVERTY_ESTIMATION`
         - set the input  to `test_data` -- giving access to all datasets.
      - same for output. use `test_output`
        -  instead of `test_output/DA_POVERTY_ESTIMATION`
- The preferred TA2 is working off the problem path in the SearchSolutionsRequest
- However, this limits the app to a single user and involves clearing out old data from `test_output`--especially when switching datasets.
- Update for TA2TA3 API: specify output directories used for the search
--- 
List of data to prune / clear when switching datasets:
- [x] TA2/TA3 output directories.  e.g. clear contents of these 3, but keep actual directories:
   ```
  "D3MOUTPUTDIR":"/ravens_volume/test_output/38_sick",
   "D3MLOCALDIR":"/ravens_volume/test_output/38_sick/local_dir",
   "D3MSTATICDIR":"/ravens_volume/test_output/38_sick/static_dir"
   ```
- [x] EndSearches. Use GRPC StoredRequests to end any searches not already ended.  Filter by user
- [x] Clear GRPC StoredRequests/StoredResponses for the user
- [x] Clear Behavioral Logs (making sure they've been written somewhere persistent)
- [x] Workspaces - Clear all user workspaces
- [x] Go to Pebbles Page

- [x] Mongo: Clear it?

## select dataset page

- [x] Limit this to the 3 known datasets.  
   - [x] Allow re-configuration via the admin if necessary
   - [x] Fixtures to load the initial 3
- [x] Update to the new D3M config dataset
- [x] Switch back to the pebbles page
Additional data to clear

**Comment by raprasad** [comment]
- [ ] Export/Flush logs before reset

**Comment by tercer** [comment]
Was already very useful for B Wilson's demo.
