### ISSUE TITLE
Reference line in predicted versus actual results plot

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#727]
On predicted vs. actual, line should be y=x, not corners of bounding box (eg use {min(y,\hat{y}),min(y,\hat{y})} to {max(y,\hat{y}), max(y,\hat{y})} instead of {min(\hat{y}),min(y)} to {max(\hat{y}),max(y)} ) :

<img width="936" alt="61555908-70407200-aa2e-11e9-997d-cb2ea03cf49b" src="https://user-images.githubusercontent.com/2085037/68866302-302e8a80-06c2-11ea-8f3d-d7ab8c96204f.png">
<img width="931" alt="62479417-713a0900-b77b-11e9-93a6-3f54b35dfdef" src="https://user-images.githubusercontent.com/2085037/68866307-315fb780-06c2-11ea-933d-e619f4b9e00b.png">

**Comment by Shoeboxam** [comment]
Fixed in `automl-backends`
