### ISSUE TITLE
Title placement in confusion matrix

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#728]
Confusion matrix title off-center/cropped (in accred_reduced with many categories). 

<img width="826" alt="61483110-21310900-a96a-11e9-8eae-723156f9b661" src="https://user-images.githubusercontent.com/2085037/68866389-5522fd80-06c2-11ea-9d07-cf37025255ca.png">

**Comment by Shoeboxam** [comment]
Switched to Vega.
