### ISSUE TITLE
upgrade ta2-ta3 api

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#73]
Bump version and related code to: https://gitlab.com/datadrivendiscovery/ta3ta2-api/tags/v2017.12.20

**Comment by raprasad** [comment]
Changes:
- UpdateProblemSchema
    - [ ] no longer exists
- CreatePipelines
    - [ ] PipelineCreateRequest - syntax changed
- Execute Pipeline
    - [ ] PipelineExecuteRequest - syntax changed

**Comment by raprasad** [comment]
## ui notes

- output type, only undefined is valid, not real, etc

**Comment by raprasad** [comment]
1. PipelineExecuteRequest
    - [ ] remove predictFeatures and add datasetUri
1. PipelineExecuteResult
   - [ ] change result_uris to singular

**Comment by tercer** [comment]
Cancel Pipelines poses an interesting question as to where that might belong on the UI end.  It is like canceling the triggering of the estimate button.  I imagine if we embellish the estimate button with a progress bar/time to completion estimate (which is something I played with) then we might put a cancel or "X" near the progress bar.

**Comment by raprasad** [comment]
- [ ] for UI dev, update grpc test form to show url on page

**Comment by raprasad** [comment]
Is there a way to get the list of types directly into the UI?  e.g. from core.proto to API to UI
\

**Comment by tercer** [comment]
There's no obvious way presently to get the types/subtypes/metrics from either the TA2TA3 API, TA1TA2 API, or from the Lincoln Labs schema.  This has been discussed though from the TA2TA3 perspective.
