### ISSUE TITLE
Reconcile mongo counts with dataset counts

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#730]

**Comment by Shoeboxam** [comment]
I switched the data import mechanism from an individual record insertion loop to mongoimport/mongoexport. Therefore queries will not be run on the collection until import has completed. This should reconcile counts. Previous versions would toss up the record count based on the current status of the import, regardless of its stage of completion.

A side effect of this is preprocess will appear to be slower to compute. Previously, preprocess was run twice, once after a few hundred records are in the db, and once after import is complete. The statistics would animate between the preprocesses at each stage. Currently, only one preprocess is computed once the collection finishes importing.
