### ISSUE TITLE
EFD plots broken continuous variables

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#751]
EFD plots are not generating for continuous variables (checked safari and chrome).  Here is what results for AutoMPG:

<img width="882" alt="Screen Shot 2019-12-02 at 10 14 09 AM" src="https://user-images.githubusercontent.com/2085037/69970676-a289d200-14ec-11ea-9ae4-6cd8e199bffb.png">

**Comment by Shoeboxam** [comment]
Having a stack trace (in this case, the first one in the browser console) is useful for this kind of issue. Fixed in a testing round.
