### ISSUE TITLE
Fitted versus actual graphs 

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#753]
For continuous variables, some issues cropping up in fitted versus actual graphs:

No plot points in College Debt:
<img width="965" alt="Screen Shot 2019-12-02 at 10 24 14 AM" src="https://user-images.githubusercontent.com/2085037/69971919-a61e5880-14ee-11ea-91fb-e4ada68f1b8d.png">

This is AutosMPG.  Look at the legend.  There are no singletons?  Every data location has at least two identical observations (if legend correct)?
<img width="292" alt="Screen Shot 2019-12-02 at 9 57 56 AM" src="https://user-images.githubusercontent.com/2085037/69971929-ad456680-14ee-11ea-9af7-c2752ccfb26d.png">

**Comment by Shoeboxam** [comment]
"Fixed" by making getData complete promises serially. If we switch the Django db engine to postgres we could re-enable parallel mongo queries via the transactional database operations in import_dataset.
