### ISSUE TITLE
upgrade TA2TA3 API to v2019.12.4

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#759]
https://gitlab.com/datadrivendiscovery/ta3ta2-api/-/tags

https://gitlab.com/datadrivendiscovery/ta3ta2-api/blob/v2019.12.4/HISTORY.md

**Comment by raprasad** [comment]
- HelloResponse has switched. 

## System start up
  - Previously, Hello call was used to see that the TA2 was up and running. TwoRavens did not continue without this.
  - Now: need new TA2 "alive" call to ensure the TA2/TA3 **connection** is generally working, even if the TA1 primitizes are not loaded.

## D3M Solve 
  - D3M TA2 "solve" button needs to check that HelloResponse is working, meaning that TA2 is ready to solve
