### ISSUE TITLE
Explore plots break on TR12 

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#762]
If the datasets are too large, the explore plots seem to come up empty.  Experimenting in one dataset, I found they were breaking with 5000 observations, but working with 1000, so somewhere in there seems to be a breaking point.

**Comment by tercer** [comment]
Axes are created, but no data appears.  Seems to happen at lower N for explore of discovered problems.

<img width="768" alt="Screen Shot 2019-12-06 at 7 18 31 AM" src="https://user-images.githubusercontent.com/2085037/70322666-b4bf8500-17f8-11ea-8f2f-65faaecde8c0.png">

**Comment by tercer** [comment]
Is not a scale problem.

**Comment by tercer** [comment]
Seems to be a general issue on explore plots when in discovery.

**Comment by aaron-lebo** [comment]
What steps need to be taken to cause this? I've selected this dataset and a problem via discovery, but am unable to produce it.

**Comment by aaron-lebo** [comment]
There is a mix of issues here. 

1. The mongodb query is not getting built properly in master, but that fix is already in on develop.
2. There is a browser exception on Firefox that prevents rendering on larger combinations of variables. This is difficult to debug and I don't believe related to 2ravens. Chrome works, I'm unsure about Safari or others.

This is another example in the wild: https://github.com/naver/billboard.js/issues/399

3. There is a separate bug related to bar plots, but this is fixable.
