### ISSUE TITLE
Odd Vegas Behaviour

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#776]
<img width="822" alt="Screen Shot 2020-01-07 at 11 00 56 AM" src="https://user-images.githubusercontent.com/2085037/71909018-139c5500-313d-11ea-9639-7bba1590acf6.png">

**Comment by tercer** [comment]
From TR31_PRIO_GRID

**Comment by tercer** [comment]
x-axis seems to start at 0, not min(year)

**Comment by tercer** [comment]
This also happens on the predicted vs. actuals plot.  

<img width="948" alt="Screen Shot 2020-01-16 at 4 41 25 AM" src="https://user-images.githubusercontent.com/2085037/72512924-8f239380-381a-11ea-8d6d-7c66e7060748.png">

**Comment by tercer** [comment]
Same as #809

**Comment by tercer** [comment]
Fixed now on results (predicted vs. actuals)

**Comment by Shoeboxam** [comment]
Fixed in 994ce2d0ae14cf0874696592a60e313b3dd4d440
