### ISSUE TITLE
Manipulate and Results Mode should have a subsample ability

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#777]
If one needs faster performance, should be a quick way to subsample the dataset down in manipulate.

**Comment by tercer** [comment]
Already exists internally.  Need to expose to user.

**Comment by Shoeboxam** [comment]
I'm hesitant to add a manipulations step that invokes mongo's sample aggregation, because then the pipeline is no longer deterministic. Doing so could cause counts, plots, statistics, etc to update noisily. Sampling limits could instead be baked into a test/train data split collection.
