### ISSUE TITLE
Discovered problems having no metric or wrong metric

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#787]
The list of discovered problems is being populated with no metric.  And so the metric being used is either by default wrong (or just copied from problem 0, the original problem of the seed dataset).

<img width="706" alt="Screen Shot 2020-01-17 at 10 48 18 AM" src="https://user-images.githubusercontent.com/2085037/72625625-1d7d3f80-3917-11ea-8685-020405407dbf.png">
<img width="647" alt="Screen Shot 2020-01-17 at 10 47 58 AM" src="https://user-images.githubusercontent.com/2085037/72625627-1d7d3f80-3917-11ea-84d1-81eb72ebc604.png">

**Comment by raprasad** [comment]
Fixed here: https://github.com/TwoRavens/TwoRavens/commit/428a86a58182f80bf291bafd0935b2fd9f964950#diff-fe1837aa94235d22ab76325de53d9eaaR1439
