### ISSUE TITLE
reutilize `Mark Problem Finished` as a stop search button.

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#801]
Currently, doing a lot of rebooting the docker image when want to start a new search.  Need to make something similar available in cloud deployment.  Should compare end search and stop search calls, and check which are listened to in choice TA2.

**Comment by Shoeboxam** [comment]
There is a octagon exclamation mark on the footer in results mode that makes calls the TA2 stop for all known pipeline IDs. Keep in mind that pipeline IDs from prior workspaces (page reloads) may still be running in the cloud, but the frontend application has no knowledge of them, so it cannot craft the necessary apis to kill them.
