### ISSUE TITLE
Explore plots using 0 instead of min(variable)

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#809]
Lots of the explore plots have 0 as the min value on the axis, rather than something close to the actual min value of the variable.  Sometimes this works out, and sometimes looks terrible:

<img width="781" alt="Screen Shot 2020-01-25 at 11 33 28 PM" src="https://user-images.githubusercontent.com/2085037/73130701-6db96900-3fcb-11ea-9388-3cf20baa0225.png">

**Comment by tercer** [comment]
Same as #776

**Comment by Shoeboxam** [comment]
Fixed in 994ce2d0ae14cf0874696592a60e313b3dd4d440
