### ISSUE TITLE
Left panel doubling in model mode

### ISSUE THREAD

**Issue by tercer** [TwoRavens/TwoRavens#817]
This happens sometimes when returning to model mode from a long session in results mode:

<img width="384" alt="Screen Shot 2020-01-29 at 6 09 32 PM" src="https://user-images.githubusercontent.com/2085037/73414105-a48cc900-42c2-11ea-95ff-07025add3572.png">

**Comment by Shoeboxam** [comment]
When you see this bug again, can you grab the first error from the console? Tends to happen when there is a bug when building the virtual dom for mithril. The error when building the virtual dom causes a desync between the virtual dom and actual dom, so mithril inserts the actual dom again.
