### ISSUE TITLE
Solver issues

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#898]
### not getting solutions with NYU TA2 
  - Sahel datasets

### no accuracy with classification problems. (@voidstrike is checking)
  - Sahel grid dataset, `any_violence` as the target

### variable importance 
  - barplots not there

### peek issue with Western Sahel Grid
   - [x] duplicate `pg_id`, something off in Peek
       - downloaded data is correct
       - data written out is also correct

### Event data

- [x] Send data to NYU. 
    - error: "No default D3MConfiguration set."~~
- [ ] Subset numbers not working when switching datasets.
    - e.g. Works from A->B, but not back B->A
    - review with @vjdorazio, may be that older version was up

**Comment by tercer** [comment]
Confirming, model comparison feature importance barplots have disappeared:

<img width="1413" alt="Screen Shot 2020-07-21 at 2 22 54 PM" src="https://user-images.githubusercontent.com/2085037/88092031-d9852480-cb5d-11ea-946b-9fdcfeb9fc46.png">

Actually, all feature importance barplots seem to have disappeared, regardless of whether in model comparison mode:

<img width="1407" alt="Screen Shot 2020-07-21 at 2 24 52 PM" src="https://user-images.githubusercontent.com/2085037/88092159-0e917700-cb5e-11ea-9019-ddd0c13f7bda.png">
