### ISSUE TITLE
write discovered problem file

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/TwoRavens#91]
1. Allow the user to insert that within the problem schema
    - Where should it get inserted?  At the end? Somewhere else?
1. Write it to a location
    - What should the file be named?
    - Where should the file be written?
       - Where within config directories?
       - pipeline_logs_root? executables_root?

### Case 1: Solve this problem

  - Send to TA2
  - Write to File

### Case 2: Record this problem
 
  - Write to File
  - See working group: discovered problem spec.

**Comment by tercer** [comment]
The file was decided to be composed of:
1. a problem description .json, following the problem schema 
2. a CreatePipeline call .json, serializing into JSON a gRPC call.

There should be one separate file for each problem discovered.
The files should be written to a location found in the `config_search.json` file, with field name `user_problems_root`.

See brief spec here:
https://datadrivendiscovery.org/wiki/display/gov/JSON+inputs+file+syntax

**Comment by tercer** [comment]
Is working on NIST architecture.
